// AUTH_SINGIN: '[AUTH] SIGN IN',
export const TYPES = {
  /* Generals */
  ERROR_TO_FETCH: '[ERROR] ERROR TO FETCH',
  IS_LOADING: '[LOADING] IS LOADING',
  AUTH_CHECKING: '[AUTH] CHECKING',
  AUTH_LOGIN: '[AUTH] LOGIN',
  AUTH_LOGOUT: '[AUTH] LOGOUT',

  /* Products */
  PRODUCT_GET: '[PRODUCT] GET',
  PRODUCT_GET_ID: '[PRODUCT] GET BY ID',
  PRODUCT_GET_DETAILS: '[PRODUCT] GET DETAILS',
  PRODUCT_SEARCH: '[PRODUCT] SEARCH',

  /* Cart */
  ADD_TO_CART: '[CART] CREATE',
  GET_USER_CART: '[CART] GET USER CART',

  /* Categories */
  CATEGORY_GET: '[CATEGORY] GET',
};
