// AUTH_SINGIN: '[AUTH] SIGN IN',
export const TYPES = {
  /* Generals */
  ERROR_TO_FETCH: '[ERROR] ERROR TO FETCH',
  IS_LOADING: '[LOADING] IS LOADING',
  AUTH_CHECKING: '[AUTH] CHECKING',
  AUTH_LOGIN: '[AUTH] LOGIN',
  AUTH_LOGOUT: '[AUTH] LOGOUT',

  /* Products */
  PRODUCT_GET: '[PRODUCT] GET',
  PRODUCT_GET_ID: '[PRODUCT] GET BY ID',
  PRODUCT_GET_DETAILS: '[PRODUCT] GET DETAILS',
  PRODUCT_SEARCH: '[PRODUCT] SEARCH',
  CURRENT_PAGE: '[PAGE] CURRENT',

  /* Cart */
  ADD_TO_CART: '[CART] CREATE',
  ADD_IT_ALL_UP: '[CART] ADD IT ALL UP',
  GET_USER_CART: '[CART] GET USER CART',
  COUNT_CART: '[CART] COUNT',
  REMOVE_ONE_FROM_CART: '[CART] ONE FROM CART',

  /* Categories */
  CATEGORY_GET: '[CATEGORY] GET',
  PRODUCTS_CATEGORY: '[CATEGORY] PRODUCTS CATEGORY',
};
